"""empty message

Revision ID: 051a5b80d7c6
Revises: c16c73224a66
Create Date: 2023-04-07 02:30:35.221804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '051a5b80d7c6'
down_revision = 'c16c73224a66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academics', sa.Column('education_level', sa.Enum('SCHOOL', 'HIGHSCHOOL', 'UNIVERSITY', name='enum_academic_type'), nullable=True))
    op.drop_column('academics', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academics', sa.Column('type', postgresql.ENUM('SCHOOL', 'HIGHSCHOOL', 'UNIVERSITY', name='enum_academic_type'), autoincrement=False, nullable=True))
    op.drop_column('academics', 'education_level')
    # ### end Alembic commands ###
