"""empty message

Revision ID: 28f4c5c2d06a
Revises: 2a526b49bde3
Create Date: 2023-04-06 22:46:53.766137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f4c5c2d06a'
down_revision = '2a526b49bde3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('natural_persons', sa.Column('participant_id', sa.UUID(), nullable=True))
    op.drop_constraint('natural_persons_person_id_fkey', 'natural_persons', type_='foreignkey')
    op.create_foreign_key(None, 'natural_persons', 'participants', ['participant_id'], ['id'])
    op.drop_column('natural_persons', 'person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('natural_persons', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'natural_persons', type_='foreignkey')
    op.create_foreign_key('natural_persons_person_id_fkey', 'natural_persons', 'natural_persons', ['person_id'], ['id'])
    op.drop_column('natural_persons', 'participant_id')
    # ### end Alembic commands ###
