"""empty message

Revision ID: c16c73224a66
Revises: 894b6277fa15
Create Date: 2023-04-06 23:01:55.406891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c16c73224a66'
down_revision = '894b6277fa15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identifications', sa.Column('person_id', sa.UUID(), nullable=True))
    op.drop_constraint('identifications_a_id_fkey', 'identifications', type_='foreignkey')
    op.create_foreign_key(None, 'identifications', 'natural_persons', ['person_id'], ['id'])
    op.drop_column('identifications', 'a_id')
    op.alter_column('participants', 'date_of_verification',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'date_of_verification',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('identifications', sa.Column('a_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'identifications', type_='foreignkey')
    op.create_foreign_key('identifications_a_id_fkey', 'identifications', 'natural_persons', ['a_id'], ['id'])
    op.drop_column('identifications', 'person_id')
    # ### end Alembic commands ###
